### ISSUE TITLE
Discord invile link not wotking

### ISSUE THREAD

**Issue by shishir9747** [Spicord/Spicord#29]
I can't join the discord server. also, is it support velocity?

**Comment by OopsieWoopsie** [comment]
There's no discord server, and yes, it does supports velocity.

**Comment by shishir9747** [comment]
Got this error 
[23:03:44 ERROR]: Can't create plugin spicord
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: plugin
  at org.spicord.velocity.SpicordVelocity.<init>(SpicordVelocity.java:38)
  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:31)
  while locating org.spicord.velocity.SpicordVelocity

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226) ~[server.jar:1.1.3]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097) ~[server.jar:1.1.3]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[server.jar:1.1.3]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:104) ~[server.jar:1.1.3]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:135) ~[server.jar:1.1.3]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:268) ~[server.jar:1.1.3]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:210) ~[server.jar:1.1.3]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:55) ~[server.jar:1.1.3]
Caused by: java.lang.IllegalArgumentException: plugin
        at eu.mcdb.universal.MCDB.registerCommand(MCDB.java:56) ~[?:?]
        at eu.mcdb.universal.command.UniversalCommand.register(UniversalCommand.java:89) ~[?:?]
        at org.spicord.velocity.SpicordVelocity.<init>(SpicordVelocity.java:41) ~[?:?]
        at org.spicord.velocity.SpicordVelocity$$FastClassByGuice$$3b637304.newInstance(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[server.jar:1.1.3]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:1.1.3]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:1.1.3]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[server.jar:1.1.3]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:1.1.3]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[server.jar:1.1.3]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[server.jar:1.1.3]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[server.jar:1.1.3]
        ... 6 more

**Comment by OopsieWoopsie** [comment]
Hello, thank you for reporting this issue, it should be already fixed now in release 3.1.4
https://github.com/Spicord/Spicord/releases/tag/3.1.4
Have a nice day!
