### ISSUE TITLE
Paper-746 on Java16 - Startup error

### ISSUE THREAD

**Issue by Audition-CSBlock** [Spicord/Spicord#39]
Info is in the title, here's a quick link to [openjdk16](https://github.com/openjdk/jdk16) for your convenience.

Error logs:
```java
[ERROR]: Error occurred while enabling Spicord v3.1.4 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @65efc9e2
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Unknown Source) ~[?:?]
        at org.spicord.reflect.ReflectedMethod.setAccessible(ReflectedMethod.java:63) ~[?:?]
        at org.spicord.reflect.ReflectedMethod.setAccessible(ReflectedMethod.java:26) ~[?:?]
        at org.spicord.reflect.AccessibleObject.setAccessible(AccessibleObject.java:27) ~[?:?]
        at org.spicord.util.SpicordClassLoader.<init>(SpicordClassLoader.java:37) ~[?:?]
        at org.spicord.util.SpicordClassLoader.<init>(SpicordClassLoader.java:32) ~[?:?]
        at org.spicord.LibraryLoader.<init>(LibraryLoader.java:63) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:48) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:41) ~[?:?]
        at org.spicord.bukkit.SpicordBukkit.lambda$onEnable$0(SpicordBukkit.java:36) ~[?:?]
        at org.spicord.bukkit.SpicordBukkit.onEnable(SpicordBukkit.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-746]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-746]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-746]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-746]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-746]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-746]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-746]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-746]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-746]
        at java.lang.Thread.run(Unknown Source) [?:?]
[INFO]: [Spicord] Disabling Spicord v3.1.4
```

**Comment by OopsieWoopsie** [comment]
Hello, thanks for reporting this issue, this is because of your java version.
Can you try running your server using the this option? `--add-opens java.base/java.lang=ALL-UNNAMED`

Here's an example command so you can take the idea of where to put it:
> java --add-opens java.base/java.lang=ALL-UNNAMED -Xmx4G -jar server.jar

This is supposed to prevent this issue to happen so you will be able to use the plugin while I take my time to investigate an alternative way of doing this.

**Comment by Audition-CSBlock** [comment]
I've done some troubleshooting on my own, [here](https://github.com/projectlombok/lombok/issues/2681#issuecomment-748616687)'s a solution which I've tried to implement myself but it seems to still fail.

Apparently java is dropping support for some major stuff in 16 which will eventually be fixed, I don't really know when though...

**Comment by Audition-CSBlock** [comment]
I tried starting the server with this:
> java --add-opens java.base/java.lang=ALL-UNNAMED -Xmx4G -jar server.jar

But then it still gave me an error:
```java
[INFO]: [Spicord] Enabling Spicord v3.1.4*
[ERROR]: Error occurred while enabling Spicord v3.1.4 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7659f478
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at org.spicord.reflect.ReflectedMethod.setAccessible(ReflectedMethod.java:63) ~[?:?]
        at org.spicord.reflect.ReflectedMethod.setAccessible(ReflectedMethod.java:26) ~[?:?]
        at org.spicord.reflect.AccessibleObject.setAccessible(AccessibleObject.java:27) ~[?:?]
        at org.spicord.util.SpicordClassLoader.<init>(SpicordClassLoader.java:37) ~[?:?]
        at org.spicord.util.SpicordClassLoader.<init>(SpicordClassLoader.java:32) ~[?:?]
        at org.spicord.LibraryLoader.<init>(LibraryLoader.java:63) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:48) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:41) ~[?:?]
        at org.spicord.bukkit.SpicordBukkit.lambda$onEnable$0(SpicordBukkit.java:36) ~[?:?]
        at org.spicord.bukkit.SpicordBukkit.onEnable(SpicordBukkit.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-750]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-750]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-750]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-750]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-750]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-750]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-750]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-750]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-750]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[INFO]: [Spicord] Disabling Spicord v3.1.4
```

**Comment by OopsieWoopsie** [comment]
Hi, try replacing `java.lang` to `java.net`, should look like this:

> java --add-opens java.base/java.net=ALL-UNNAMED -Xmx4G -jar server.jar

Pretty sure this will work :)

**Comment by Audition-CSBlock** [comment]
That worked for me, it would be better if this issue got fixed though. I'm still trying to figure out how to maybe get it to work but i am not familiar with java all that much. 

And please don't think i'm trying to hurry you, i'd much rather help than cause someone stress. :)

**Comment by OopsieWoopsie** [comment]
> That worked for me, it would be better if this issue got fixed though. I'm still trying to figure out how to maybe get it to work but i am not familiar with java all that much.

This will be fixed, but I first need to look for an alternative way of dynamically loading the required libraries, as including them in the Spicord.jar file is not an option. The way I do that is by adding each library file using the addURL method of the plugin class loader, that method is actually "protected", that means it can only be called from a class into the same package or within the class itself, I can't do any of those ways so I'm using the reflection api to access that method, and Java is complaining about that.
This is not hard thought, I just need some free time.

**Comment by OopsieWoopsie** [comment]
Hello! managed to fix this error :) and at the process I fixed some other errors related to a [commit](https://github.com/Spicord/Spicord/commit/5d504f6ca14afa96514d0771c0812344fe8a4a7e) I made 3 days ago to remove some old stuff... anyways, here's a build if you want to check out if the error is gone:

https://github.com/Spicord/Spicord/releases/tag/3.1.5

I tested it on Java 11 with `--illegal-access=deny`, managed to recreate the exact same error and it is now fixed and should work for Java 16 too!

**Comment by ProductiveAsparagus56** [comment]
I'll have a look when i have the time! (Soon) ill also check out the commits since i wanna know how you fixed it.

**Comment by ProductiveAsparagus56** [comment]
Just a small update, I tested it and it works like a charm! thanks a lot <3
