### ISSUE TITLE
WARN Spicord

### ISSUE THREAD

**Issue by DeriksonTM** [Spicord/Spicord#56]
Good day! ♥ The last bug was fixed, but now in the console this text.

[09:57:17] [Server thread/INFO]: [Spicord] Registered addon 'Server Information' (spicord::info) by Sheidy
[09:57:17] [Server thread/INFO]: [Spicord] Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[09:57:17] [Server thread/INFO]: [Spicord] Registered addon 'Player List' (spicord::players) by Sheidy
[09:57:17] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "org.bukkit.plugin.java.JavaPlugin.getCommand(String)" is null
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//eu.mcdb.universal.MCDB$registerBukkitCommand.<init>(MCDB.java:85)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//eu.mcdb.universal.MCDB.registerCommand(MCDB.java:48)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//eu.mcdb.universal.command.UniversalCommand.register(UniversalCommand.java:89)
[09:57:17] [Server thread/WARN]: 	at BanAnnouncer.jar//eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.onSpicordLoad(BanAnnouncerBukkit.java:52)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//org.spicord.event.EventHandler.handleSafe(EventHandler.java:10)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//org.spicord.Spicord.callEvent(Spicord.java:82)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//org.spicord.Spicord.onLoad(Spicord.java:112)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//org.spicord.SpicordLoader.load(SpicordLoader.java:74)
[09:57:17] [Server thread/WARN]: 	at Spicord.jar//org.spicord.bukkit.SpicordBukkit.lambda$onEnable$1(SpicordBukkit.java:42)
[09:57:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[09:57:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:57:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1571)
[09:57:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:516)
[09:57:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1494)
[09:57:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1282)
[09:57:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:57:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:57:17] [Server thread/INFO]: [Spicord] Starting the bots...
[09:57:17] [Server thread/INFO]: [Spicord] Starting bot 'LoweryMine'.
[09:57:18] [ForkJoinPool.commonPool-worker-3/INFO]: [Spicord] [JDA:JDA] Login Successful!
[09:57:18] [ForkJoinPool.commonPool-worker-3/WARN]: [Spicord] The addon with the id 'ban_announcer' was not found.
[09:57:19] [JDA MainWS-WriteThread/INFO]: [Spicord] [JDA:WebSocketClient] Connected to WebSocket
[09:57:19] [JDA MainWS-ReadThread/INFO]: [Spicord] [JDA:JDA] Finished Loading!

![image](https://user-images.githubusercontent.com/92043849/148042417-6507ff22-3362-48d2-ba9f-a559c9d3aba7.png)

**Comment by OopsieWoopsie** [comment]
Seems like I broke that in this commit: https://github.com/Spicord/BanAnnouncer/commit/d6049aaec7af376f1679c398adf676f81b9fa58e
I forgot to add the "commands" entry in the plugin.yml -_-
